<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AOPT3010311311" name="Default test" tests="1" failures="1" timestamp="15 Jan 2014 17:28:17 GMT" time="0.435" errors="0">
  <testcase name="createValidAccount" time="0.011" classname="com.payulatam.samples.bank.test.service.AccountDaoTest">
    <failure type="java.lang.AssertionError" message="
  Expectation failure on verify:
    GigaSpace.readById(class com.payulatam.samples.bank.common.Client, &amp;quot;id&amp;quot;): expected: 1, actual: 0
    GigaSpace.write(isA(com.payulatam.samples.bank.common.Account), isA(com.gigaspaces.client.WriteModifiers)): expected: 1, actual: 0">
      <![CDATA[java.lang.AssertionError: 
  Expectation failure on verify:
    GigaSpace.readById(class com.payulatam.samples.bank.common.Client, "id"): expected: 1, actual: 0
    GigaSpace.write(isA(com.payulatam.samples.bank.common.Account), isA(com.gigaspaces.client.WriteModifiers)): expected: 1, actual: 0
	at org.easymock.internal.MocksControl.verify(MocksControl.java:226)
	at org.easymock.EasyMock.verify(EasyMock.java:2080)
	at com.payulatam.samples.bank.test.service.AccountDaoTest.createValidAccount(AccountDaoTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- createValidAccount -->
</testsuite> <!-- Default test -->
